DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	`id` BIGINT (20) AUTO_INCREMENT COMMENT '主键',
	`username` CHAR (50) DEFAULT NULL COMMENT '用户名',
	`pwd` CHAR (40) DEFAULT NULL COMMENT '密码',
	`mark` TINYINT DEFAULT 0 COMMENT '状态[0:MC,1:ZG,2:AQL,1:NAXX]',
	`type` CHAR (12) DEFAULT NULL COMMENT '职业',
	`dynamic` INT DEFAULT 0 COMMENT '动态',
	`consume` INT DEFAULT 0 COMMENT '消费',
	`surplus` INT DEFAULT 0 COMMENT '剩余',
	`role` CHAR (12) DEFAULT NULL COMMENT '角色',
	`desc` VARCHAR (128) DEFAULT NULL COMMENT '备注',
	`createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY (`id`),
	KEY (`username`),
	KEY (`type`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '用户表';

DROP TABLE IF EXISTS `dkp`;
CREATE TABLE `dkp` (
	`id` BIGINT  AUTO_INCREMENT COMMENT '主键',
	`uid` BIGINT NOT NULL COMMENT '用户ID',
	`username` CHAR (50) DEFAULT NULL COMMENT '用户名',
	`role` CHAR (12) DEFAULT NULL COMMENT '职业',
	`type` CHAR (12) DEFAULT NULL COMMENT '消费类型',
	`num` INT DEFAULT 0 COMMENT '分值',
	`info` VARCHAR (256) DEFAULT NULL COMMENT '备注',
	`createTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY (`id`),
	KEY (`username`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'DKP表';
